branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: WebpackProject
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git
